/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/messages/{groupid}": {
    /** Gets Last Messages Sent In a Chat */
    get: {
      parameters: {
        query?: {
          limit?: number;
          below?: boolean;
          start?: number;
        };
        path: {
          groupid: string;
        };
      };
      responses: {
        /** @description Fetching List Of articles */
        200: {
          content: {
            "application/json": components["schemas"]["Message"][];
          };
        };
      };
    };
    post: {
      parameters: {
        path: {
          groupid: number;
        };
      };
      responses: {
        /** @description Fetching Sequential Messages In Group Chat */
        200: {
          content: {
            "application/json": components["schemas"]["MessageRequest"];
          };
        };
      };
    };
  };
  "/searched/messages/{groupid}": {
    get: {
      parameters: {
        query?: {
          search?: string[];
        };
      };
      responses: {
        /** @description Searching Messages In Group Chat */
        200: {
          content: {
            "application/json": components["schemas"]["Message"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Message: {
      messageid?: number;
      groupid: string;
      sendor: string;
      content: string;
      sent_at: string;
    };
    MessageRequest: {
      groupid: string;
      content: string;
      sent_at: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
