openapi: 3.0.0
info:
  title: Messages API
  version: 1.0.0
paths:
  /messages/{groupid}:
    get:
      parameters:
        - in: path
          name: groupid
          required: true
          schema:
            type: integer
        - in: query
          name: limit
          required: false
          schema:
            type: integer
            default: 50
            minimum: 0
        - in: query
          name: below
          required: false
          schema:
            type: boolean
            default: false
        - in: query
          name: timestamp
          required: false
          schema:
            type: integer
            minimum: 0
      summary: Gets Last Messages Sent In a Chat
      responses:
        "200":
          description: Fetching List Of articles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Message"
    post:
      parameters:
        - in: path
          name: groupid
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Fetching Sequential Messages In Group Chat
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
  /searched/messages/{groupid}:
    get:
      parameters:
        - in: query
          name: search
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: Searching Messages In Group Chat
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
components:
  schemas:
    Message:
      type: object
      properties:
        id:
          type: integer
        groupid:
          type: integer
        sendor:
          type: string
        content:
          type: string
        sent_at:
          type: string
      required:
        - id
        - groupid
        - sendor
        - content
        - sent_at
